export const KmsTokens = {
  KB_REPOSITORY: Symbol("KB_REPOSITORY"),
  ARTICLE_REPOSITORY: Symbol("ARTICLE_REPOSITORY"),
  SEARCH_SERVICE: Symbol("SEARCH_SERVICE"),
  ADMIN_KB_SERVICE: Symbol("ADMIN_KB_SERVICE"),
  ARTICLE_SERVICE: Symbol("ARTICLE_SERVICE"),
} as const;
