export const RetrieverTokens = {
  TEMP_VECTOR_STORE: Symbol("TEMP_VECTOR_STORE"),
  PERSISTENCE_VECTOR_STORE: Symbol("KNOWLEDGE_VECTOR_STORE"),
  KNOWLEDGE_RETRIEVER: Symbol("KNOWLEDGE_RETRIEVER"),
  TEMP_RETRIEVER: Symbol("TEMP_RETRIEVER"),
} as const;
